package com.zhuwm.mybatis.entity.zrxtcs;

import java.math.BigDecimal;
import java.util.Date;

public class Projects {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZRXTCS.PROJECTS.PROJECT_ID
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	private Long projectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZRXTCS.PROJECTS.PROJECT_CODE
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	private String projectCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZRXTCS.PROJECTS.PROJECT_NAME
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	private String projectName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZRXTCS.PROJECTS.PARENT_PROJECT_ID
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	private Long parentProjectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZRXTCS.PROJECTS.PROJECT_TYPE
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	private String projectType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZRXTCS.PROJECTS.SALES_CHANNEL
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	private String salesChannel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZRXTCS.PROJECTS.ID_PATH
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	private String idPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZRXTCS.PROJECTS.STATUS
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZRXTCS.PROJECTS.RISK_EVALUATION_PAPER
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	private String riskEvaluationPaper;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZRXTCS.PROJECTS.RISK_NOTICE_AGREEMENT
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	private String riskNoticeAgreement;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZRXTCS.PROJECTS.CREATE_BY
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	private Long createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZRXTCS.PROJECTS.CREATE_TIME
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZRXTCS.PROJECTS.UPDATE_BY
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	private Long updateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZRXTCS.PROJECTS.UPDATE_TIME
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZRXTCS.PROJECTS.RELATED_ORG_NAME
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	private String relatedOrgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZRXTCS.PROJECTS.CONTRACT_RATE
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	private BigDecimal contractRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZRXTCS.PROJECTS.ORG_RISK_EVALUATION_PAPER
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	private String orgRiskEvaluationPaper;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZRXTCS.PROJECTS.PROJECT_ID
	 * @return  the value of ZRXTCS.PROJECTS.PROJECT_ID
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public Long getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZRXTCS.PROJECTS.PROJECT_ID
	 * @param projectId  the value for ZRXTCS.PROJECTS.PROJECT_ID
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZRXTCS.PROJECTS.PROJECT_CODE
	 * @return  the value of ZRXTCS.PROJECTS.PROJECT_CODE
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public String getProjectCode() {
		return projectCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZRXTCS.PROJECTS.PROJECT_CODE
	 * @param projectCode  the value for ZRXTCS.PROJECTS.PROJECT_CODE
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public void setProjectCode(String projectCode) {
		this.projectCode = projectCode == null ? null : projectCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZRXTCS.PROJECTS.PROJECT_NAME
	 * @return  the value of ZRXTCS.PROJECTS.PROJECT_NAME
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public String getProjectName() {
		return projectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZRXTCS.PROJECTS.PROJECT_NAME
	 * @param projectName  the value for ZRXTCS.PROJECTS.PROJECT_NAME
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public void setProjectName(String projectName) {
		this.projectName = projectName == null ? null : projectName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZRXTCS.PROJECTS.PARENT_PROJECT_ID
	 * @return  the value of ZRXTCS.PROJECTS.PARENT_PROJECT_ID
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public Long getParentProjectId() {
		return parentProjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZRXTCS.PROJECTS.PARENT_PROJECT_ID
	 * @param parentProjectId  the value for ZRXTCS.PROJECTS.PARENT_PROJECT_ID
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public void setParentProjectId(Long parentProjectId) {
		this.parentProjectId = parentProjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZRXTCS.PROJECTS.PROJECT_TYPE
	 * @return  the value of ZRXTCS.PROJECTS.PROJECT_TYPE
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public String getProjectType() {
		return projectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZRXTCS.PROJECTS.PROJECT_TYPE
	 * @param projectType  the value for ZRXTCS.PROJECTS.PROJECT_TYPE
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public void setProjectType(String projectType) {
		this.projectType = projectType == null ? null : projectType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZRXTCS.PROJECTS.SALES_CHANNEL
	 * @return  the value of ZRXTCS.PROJECTS.SALES_CHANNEL
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public String getSalesChannel() {
		return salesChannel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZRXTCS.PROJECTS.SALES_CHANNEL
	 * @param salesChannel  the value for ZRXTCS.PROJECTS.SALES_CHANNEL
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public void setSalesChannel(String salesChannel) {
		this.salesChannel = salesChannel == null ? null : salesChannel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZRXTCS.PROJECTS.ID_PATH
	 * @return  the value of ZRXTCS.PROJECTS.ID_PATH
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public String getIdPath() {
		return idPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZRXTCS.PROJECTS.ID_PATH
	 * @param idPath  the value for ZRXTCS.PROJECTS.ID_PATH
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public void setIdPath(String idPath) {
		this.idPath = idPath == null ? null : idPath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZRXTCS.PROJECTS.STATUS
	 * @return  the value of ZRXTCS.PROJECTS.STATUS
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZRXTCS.PROJECTS.STATUS
	 * @param status  the value for ZRXTCS.PROJECTS.STATUS
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZRXTCS.PROJECTS.RISK_EVALUATION_PAPER
	 * @return  the value of ZRXTCS.PROJECTS.RISK_EVALUATION_PAPER
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public String getRiskEvaluationPaper() {
		return riskEvaluationPaper;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZRXTCS.PROJECTS.RISK_EVALUATION_PAPER
	 * @param riskEvaluationPaper  the value for ZRXTCS.PROJECTS.RISK_EVALUATION_PAPER
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public void setRiskEvaluationPaper(String riskEvaluationPaper) {
		this.riskEvaluationPaper = riskEvaluationPaper == null ? null : riskEvaluationPaper.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZRXTCS.PROJECTS.RISK_NOTICE_AGREEMENT
	 * @return  the value of ZRXTCS.PROJECTS.RISK_NOTICE_AGREEMENT
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public String getRiskNoticeAgreement() {
		return riskNoticeAgreement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZRXTCS.PROJECTS.RISK_NOTICE_AGREEMENT
	 * @param riskNoticeAgreement  the value for ZRXTCS.PROJECTS.RISK_NOTICE_AGREEMENT
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public void setRiskNoticeAgreement(String riskNoticeAgreement) {
		this.riskNoticeAgreement = riskNoticeAgreement == null ? null : riskNoticeAgreement.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZRXTCS.PROJECTS.CREATE_BY
	 * @return  the value of ZRXTCS.PROJECTS.CREATE_BY
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public Long getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZRXTCS.PROJECTS.CREATE_BY
	 * @param createBy  the value for ZRXTCS.PROJECTS.CREATE_BY
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZRXTCS.PROJECTS.CREATE_TIME
	 * @return  the value of ZRXTCS.PROJECTS.CREATE_TIME
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZRXTCS.PROJECTS.CREATE_TIME
	 * @param createTime  the value for ZRXTCS.PROJECTS.CREATE_TIME
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZRXTCS.PROJECTS.UPDATE_BY
	 * @return  the value of ZRXTCS.PROJECTS.UPDATE_BY
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public Long getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZRXTCS.PROJECTS.UPDATE_BY
	 * @param updateBy  the value for ZRXTCS.PROJECTS.UPDATE_BY
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public void setUpdateBy(Long updateBy) {
		this.updateBy = updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZRXTCS.PROJECTS.UPDATE_TIME
	 * @return  the value of ZRXTCS.PROJECTS.UPDATE_TIME
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZRXTCS.PROJECTS.UPDATE_TIME
	 * @param updateTime  the value for ZRXTCS.PROJECTS.UPDATE_TIME
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZRXTCS.PROJECTS.RELATED_ORG_NAME
	 * @return  the value of ZRXTCS.PROJECTS.RELATED_ORG_NAME
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public String getRelatedOrgName() {
		return relatedOrgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZRXTCS.PROJECTS.RELATED_ORG_NAME
	 * @param relatedOrgName  the value for ZRXTCS.PROJECTS.RELATED_ORG_NAME
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public void setRelatedOrgName(String relatedOrgName) {
		this.relatedOrgName = relatedOrgName == null ? null : relatedOrgName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZRXTCS.PROJECTS.CONTRACT_RATE
	 * @return  the value of ZRXTCS.PROJECTS.CONTRACT_RATE
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public BigDecimal getContractRate() {
		return contractRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZRXTCS.PROJECTS.CONTRACT_RATE
	 * @param contractRate  the value for ZRXTCS.PROJECTS.CONTRACT_RATE
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public void setContractRate(BigDecimal contractRate) {
		this.contractRate = contractRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZRXTCS.PROJECTS.ORG_RISK_EVALUATION_PAPER
	 * @return  the value of ZRXTCS.PROJECTS.ORG_RISK_EVALUATION_PAPER
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public String getOrgRiskEvaluationPaper() {
		return orgRiskEvaluationPaper;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZRXTCS.PROJECTS.ORG_RISK_EVALUATION_PAPER
	 * @param orgRiskEvaluationPaper  the value for ZRXTCS.PROJECTS.ORG_RISK_EVALUATION_PAPER
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	public void setOrgRiskEvaluationPaper(String orgRiskEvaluationPaper) {
		this.orgRiskEvaluationPaper = orgRiskEvaluationPaper == null ? null : orgRiskEvaluationPaper.trim();
	}
}