package com.zhuwm.mybatis.mapper;

import com.zhuwm.mybatis.entity.zrxtcs.Projects;

public interface ProjectsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZRXTCS.PROJECTS
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	int deleteByPrimaryKey(Long projectId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZRXTCS.PROJECTS
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	int insert(Projects record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZRXTCS.PROJECTS
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	int insertSelective(Projects record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZRXTCS.PROJECTS
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	Projects selectByPrimaryKey(Long projectId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZRXTCS.PROJECTS
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	int updateByPrimaryKeySelective(Projects record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZRXTCS.PROJECTS
	 * @mbggenerated  Wed Feb 24 21:29:16 CST 2016
	 */
	int updateByPrimaryKey(Projects record);
}